# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded xoRET::GUI 0.1.2 [list source [file join $dir gui.xotcl]]
package ifneeded xoRET::GUI::CMenu 0.1 [list source [file join $dir cmenu.xotcl]]
package ifneeded xoRET::GUI::Create 0.1 [list source [file join $dir create.xotcl]]
package ifneeded xoRET::GUI::Dialog 0.2 [list source [file join $dir dialog.xotcl]]
package ifneeded xoRET::GUI::Edit 0.1 [list source [file join $dir edit.xotcl]]
package ifneeded xoRET::GUI::ImExport 0.2.1 [list source [file join $dir imexport.xotcl]]
package ifneeded xoRET::GUI::Traces 0.1 [list source [file join $dir traces.xotcl]]
package ifneeded xoRET::GUI::Tree 0.2 [list source [file join $dir tree.xotcl]]
