# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded xoRET 0.2 [list source [file join $dir Manager.xotcl]]
package ifneeded xoRET::Condition 0.1.2 [list source [file join $dir Condition.xotcl]]
package ifneeded xoRET::ContextConstraint 0.1.2 [list source [file join $dir ContextConstraint.xotcl]]
package ifneeded xoRET::Object 0.1.1 [list source [file join $dir xoRETObject.xotcl]]
package ifneeded xoRET::Objective 0.1.1 [list source [file join $dir Objective.xotcl]]
package ifneeded xoRET::Obstacle 0.1.1 [list source [file join $dir Obstacle.xotcl]]
package ifneeded xoRET::Permission 0.2.2 [list source [file join $dir Permission.xotcl]]
package ifneeded xoRET::Recreator 0.2 [list source [file join $dir xoRET_RecreatorVisitor.xotcl]]
package ifneeded xoRET::Role 0.2.2 [list source [file join $dir Role.xotcl]]
package ifneeded xoRET::Scenario 0.2 [list source [file join $dir Scenario.xotcl]]
package ifneeded xoRET::Step 0.1.1 [list source [file join $dir Step.xotcl]]
package ifneeded xoRET::Task 0.1.1 [list source [file join $dir Task.xotcl]]
package ifneeded xoRET::TraceTypeImport 0.1 [list source [file join $dir TraceTypeImport.xotcl]]
package ifneeded xoRET::WorkProfile 0.1.1 [list source [file join $dir WorkProfile.xotcl]]
